alias: "Notify on Power Cut Resolved"
description: "Send a notification when a power cut is resolved."
trigger:
  - platform: state
    entity_id: sensor.northern_powergrid_power_cut_count
    to: "0"
condition: []
action:
  - service: notify.notify
    data_template:
      title: "Power Cut Resolved"
      message: >
        A power cut has been resolved in your area.
        Reference: {{ states('sensor.northern_powergrid_power_cut_latest_event') }}
        Start Time: {{ state_attr('sensor.northern_powergrid_power_cut_latest_event', 'start_time') }}
        Estimated Restoration: {{ state_attr('sensor.northern_powergrid_power_cut_latest_event', 'estimated_restoration') }}
        Status: {{ state_attr('sensor.northern_powergrid_power_cut_latest_event', 'status') }}
        Reason: {{ state_attr('sensor.northern_powergrid_power_cut_latest_event', 'reason') }}
        Nature: {{ state_attr('sensor.northern_powergrid_power_cut_latest_event', 'nature') }}
mode: single
